scan_timeout = 60
add_newline = false

# red = #DA627D
# orage = #FCA17D
# cyan = #86BBD8
# aqua = #06969A

format = """
[ ](bg:red)\
[](bg:green fg:red)\
$directory\
[](bg:yellow fg:green)\
$git_branch\
$git_status\
[](bg:blue fg:yellow)\
[](fg:blue)\
$aws\
$cmake\
$cmd_duration\
$cobol\
$conda\
$crystal\
$daml\
$dart\
$deno\
$docker_context\
$dotnet\
$elixir\
$elm\
$erlang\
$gcloud\
$golang\
$haskell\
$helm\
$hg_branch\
$java\
$julia\
$kotlin\
$kubernetes\
$lua\
$memory_usage\
$nim\
$nix_shell\
$nodejs\
$ocaml\
$openstack\
$package\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$red\
$ruby\
$rust\
$scala\
$spack\
$sudo\
$swift\
$terraform\
$vagrant\
$vlang\
$zig
$character
"""

[directory]
style = "bg:green fg:black"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = "[$user ]($style)"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#DA627D fg:white"
format = "[🕘$time ]($style)"

[character]
success_symbol = "[❯](bold purple)[❯](bold yellow)[❯](bold green)"
error_symbol = "[✘](bold red)"

[git_branch]
style = "bg:yellow fg:black"
format = "[ $symbol$branch ]($style)"

[git_status]
style = "bg:yellow fg:black"
format = "([$all_status$ahead_behind]($style))"

[aws]
format = ' [$symbol($profile)(\($region\))( $duration )]($style) '

#[bun]
#format = " [$symbol($version)]($style) "

[c]
format = " [$symbol($version(-$name))]($style) "

[cmake]
format = " [$symbol($version)]($style) "

[cmd_duration]
format = " [⏱ $duration]($style) "

[cobol]
format = " [$symbol($version)]($style) "

[conda]
format = " [$symbol$environment]($style) "

[crystal]
format = " [$symbol($version)]($style) "

[daml]
format = " [$symbol($version)]($style) "

[dart]
format = " [$symbol($version)]($style) "

[deno]
format = " [$symbol($version)]($style) "

[docker_context]
format = " [$symbol$context]($style) "

[dotnet]
format = " [$symbol($version)(🎯 $tfm)]($style) "

[elixir]
format = ' [$symbol($version \(OTP $otp_version\))]($style) '

[elm]
format = " [$symbol($version)]($style) "

[erlang]
format = " [$symbol($version)]($style) "

[gcloud]
format = ' [$symbol$account(@$domain)(\($region\))]($style) '

[golang]
format = " [$symbol($version)]($style) "

[haskell]
format = " [$symbol($version)]($style) "
symbol = " "

[helm]
format = " [$symbol($version)]($style) "

[hg_branch]
format = " [$symbol$branch]($style) "

[java]
format = " [$symbol($version)]($style) "
symbol = " "

[julia]
format = " [$symbol($version)]($style) "

[kotlin]
format = " [$symbol($version)]($style) "

[kubernetes]
format = ' [$symbol$context( \($namespace\))]($style) '

[lua]
format = " [$symbol($version)]($style) "
symbol = " "

[memory_usage]
format = " $symbol[$ram( | $swap)]($style) "

[nim]
format = " [$symbol($version)]($style) "

[nix_shell]
format = ' [$symbol$state( \($name\))]($style) '

[nodejs]
format = " [$symbol($version) ]($style) "
symbol = " "

[ocaml]
format = ' [$symbol($version)(\($switch_indicator$switch_name\))]($style) '

[openstack]
format = ' [$symbol$cloud(\($project\))]($style) '

[package]
format = " [$symbol$version]($style) "

[perl]
format = " [$symbol($version)]($style) "

[php]
format = " [$symbol($version)]($style) "

[pulumi]
format = " [$symbol$stack]($style) "

[purescript]
format = " [$symbol($version)]($style) "

[python]
format = ' [${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '
symbol = " "

[raku]
format = " [$symbol($version-$vm_version)]($style) "

[red]
format = " [$symbol($version)]($style) "

[ruby]
format = " [$symbol($version)]($style) "

[rust]
format = " [$symbol($version)]($style) "
symbol = " "

[scala]
format = " [$symbol($version)]($style) "

[spack]
format = " [$symbol$environment]($style) "

[sudo]
format = " [as $symbol] "

[swift]
format = " [$symbol($version)]($style) "

[terraform]
format = " [$symbol$workspace]($style) "

[vagrant]
format = " [$symbol($version)]($style) "

[vlang]
format = " [$symbol($version)]($style) "

[zig]
format = " [$symbol($version)]($style) "
